name: WachauWeddings
favicon: null
layout_spectrum: 1
typography_spectrum: 0.46801
title: All-Inclusive Austrian Wedding Packages
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.8136864346452057
  rhythmicContrast: 0.5
purpose: []
